version: 0.2

phases:
  build:
    commands:
      - echo Creando paquete...
      - zip -r my-deployment-package.zip . 
      - aws lambda update-function-code --function-name labIoTGreengrassLambda --zip-file fileb://my-deployment-package.zip